-- Created a schema/database named 'playstore' and added tables 'apps' and 'reviews' from csv files.

use playstore;
select * from playstore.apps;
select* from playstore.reviews;

-- Q1: Which apps have the highest rating in the given available dataset?

select App
from playstore.apps
where Rating = (select MAX(Rating) from playstore.apps);

-- Q2: What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.

select App, Reviews, Installs
from playstore.apps
where Rating = (select MAX(Rating) from playstore.apps)
order by Reviews DESC;

-- Q3: Which app has the highest number of reviews? Also, mention the number of reviews and category of the app

select App, Category, Reviews
from playstore.apps
where Reviews = (select MAX(Reviews) from playstore.apps);

-- Q4: What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps from the google play store, the amount is considered in the revenue)

select sum(Price) as Total_Revenue
from playstore.apps;

-- Q5: Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.

select Category, SUM(Installs)
from playstore.apps
where Installs = (select MAX(Installs) from playstore.apps)
group by Category 
order by Category, SUM(Installs) DESC;


-- Q6: Which Genre has the most number of published apps?

select Genres, count(App) as app_count
from playstore.apps
group by Genres
order by app_count DESC
limit 1;

-- Q7: Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top (to avoid duplicate results use distinct)

select distinct(App), Installs
from playstore.apps
where Category = 'GAME'
group by 1, 2
order by 2 DESC;

-- Q8: Provide the list of apps that can work on android version '4.0.3 and UP'.

select App
from playstore.apps
where android_ver = '4.0.3 and UP';


-- Q9: How many apps from the given data set are free? Also, provide the number of paid apps.

select * 
from 
(select count(distinct App) as count_of_free_apps
from playstore.apps
where Price = 0) as f,
(select count(distinct App) as count_of_paid_apps
from playstore.apps
where Price > 0) as p;

-- Q10: Which is the best dating app? (Best dating app is the one having the highest number of Reviews)

select App
from playstore.apps
where Category = 'DATING' and Reviews = (select MAX(Reviews) from playstore.apps where Category = 'DATING');

-- Q11: Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app '10 best foods for you' and compare them.

select *
from
(select count(*) as count_positive_reviews
from playstore.reviews
where Sentiment = 'Positive' and App = '10 best foods for you') as p,
(select count(*) as count_negative_reviews
from playstore.reviews
where Sentiment = 'Negative' and App = '10 best foods for you') as n ;

-- Q12: Which comments of 'ASUS SuperNote' have sentiment polarity and sentiment subjectivity both as 1?

select translated_review
from playstore.reviews
where App = 'ASUS SuperNote' and sentiment_polarity = 1 and sentiment_subjectivity = 1;

-- Q13: Get all the neutral sentiment reviews for the app 'Abs Training-Burn belly fat' 

select translated_review
from playstore.reviews
where App = 'Abs Training-Burn belly fat' and sentiment = 'Neutral';

-- Q14: Extract all negative sentiment reviews for 'Adobe Acrobat Reader' with their sentiment polarity and sentiment subjectivity.

select translated_review, sentiment_polarity, sentiment_subjectivity
from playstore.reviews
where App = 'Adobe Acrobat Reader' and sentiment = 'Negative';

-- End




